host: localhost
port: 6667
nick: sama-zu
user: samazu
real: sama~zu
channels: "#test"
plugins:
  - irc
  - plugins
  -
    name: watchdog
    db: "postgres://localhost/ircbot"
  - 
    name: reminder
    db: "postgres://localhost/ircbot"
    accept_fmt: "Remind you again at %s"
  -
    name: summary
    engines: http, https, ch2, twitter
reminder
multiline: true
timeout: 500
